- name: Sleep before deployment
  hosts: localhost
  tasks:
    - pause:
        seconds: 60

- name: Deploy HAProxy
  hosts: haproxy
  roles:
    - haproxy
  when: groups['haproxy'] | length > 0

- name: Setup Kubernetes Cluster
  import_playbook: k8s-setup.yml
  when: (groups['masters'] | length > 0) and (groups['workers'] | length > 0)

- name: Deploy NFS server
  hosts: nfs
  roles:
    - nfs
  when: groups['nfs'] | length > 0

- name: Deploy Harbor
  hosts: harbor
  roles:
    - harbor
  when: groups['monitoring'] | length > 0

- name: Deploy Monitoring (Prometheus & Grafana)
  import_playbook: helm_monitoring.yml
  when: groups['masters'] | length > 0
