---
- name: Prepare and install Kubernetes
  hosts: kube_cluster
  become: true
  roles:
    - k8s_common

- name: Initialize first master
  hosts: master_init
  become: true
  roles:
    - k8s_master

- name: Join other masters
  hosts: master_join
  become: true
  roles:
    - k8s_master_join

- name: Join worker nodes
  hosts: workers
  become: true
  roles:
    - k8s_worker

- name: Deploy metrics-server
  hosts: master_init
  become: true
  roles:
    - metrics_server