apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ hostvars['nfs']['ansible_host'] }}
    path: /srv/nfs/kubedata/hub-db-dir
  persistentVolumeReclaimPolicy: Retain
