apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-pvc
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
