# pv-nfs.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ hostvars['nfs']['ansible_host'] }}
    path: /srv/nfs/kubedata
  storageClassName: nfs

