# pv-nfs.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ nfs_server_ip }}
    path: /export/jupyterhub
  storageClassName: nfs

